# Generated by Django 5.0.6 on 2024-06-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('student_class', models.CharField(choices=[('10 a', '10 a'), ('10 b', '10 b')], max_length=50)),
                ('mobile_number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='image_student')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
